### PR TITLE
[CR] Fix only one locale per language being downloaded

### PR DESCRIPTION
**Pull request by oxixes**
The current code only allows to download one locale per language. This simple change allows to download multiple locales.

### CODE REVIEW

**Comment by izu-co** [comment]
I am currently on vacation but will review it right afterwards

**Review by izu-co — CHANGES_REQUESTED** [review]
I would add the changes inside an or statement in order to still support or versions

**Comment by oxixes** [comment]
> I would add the changes inside an or statement in order to still support or versions

I don’t understand what you mean

**Comment by oxixes** [comment]
> (the old statement) || (the new statement)

Ah ok, sure, I'll make the change ASAP

**Review by izu-co — APPROVED** [review]
Thanks for the contribution

**Pull request merged**
