### PR TITLE
Ability to reduce unnecessary bandwidth usage

### PR DESCRIPTION
**Pull request by RavensRain**
Added the dlVideoOnce option that automatically downloads the best video quality only once and then downloads the worst available video quality with the same audio quality if multiple languages are selected.
This is achieved by comparing the codecs, because if the codecs are the same, the quality will be the same.

### CODE REVIEW

**Comment by RavensRain** [comment]
I see now that I forgot to remove console.log inside the while loop.

**Review by AnidlSupport — CHANGES_REQUESTED** [review]
The `console.log`s should be removed.

Also we should Test that the feature works on every situation before setting it as default.
Therefor some tests on our end are required.

**Review by AnimeDL — APPROVED** [review]
Looks good to me, though I did notice the argument is marked for both, though only actually affects crunchy

**Review by AnidlSupport — APPROVED** [review]
LGTM

**Pull request merged**
