### PR TITLE
Upgrade to include Docker

### PR DESCRIPTION
**Pull request by edward8e**
Adding Docker to containerize in order to make it easy run without needed to deal with any configuration or setup. This is a first working draft based on the project's current state

### CODE REVIEW

**Comment by izu-co** [comment]
LGTM but I don’t have the permission to add new secrets, so I will wait with merging.

**Review by izu-co — APPROVED** [review]

**Comment by izu-co** [comment]
I’ve just gotten the permission to add secrets and I will create a docker hub account in order to upload the docker image

**Comment by edward8e** [comment]
oh nice! I'm glad you were able to get access, let me know if you need any help with the configuration.

**Comment by izu-co** [comment]
Thank you for your contribution. 

Feel free to contribute whenever you want!

**Comment by edward8e** [comment]
Glad I could help! The build steps in the Dockerfile are based on the current way the repo is setup so if it changes too much, I could always help with the updates. I'm still doing some tests on the Dockerfile, so I'll definitely push any updates if I find anything. :)

**Comment by izu-co** [comment]
Glad to hear that I've found some help.
The removed build step was used to build the gui, however only the cli was used.

**Pull request merged**
